# Generated by Django 5.2.7 on 2025-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
