# Generated by Django 5.2.7 on 2025-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_datatreinamento_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='data_treinamento',
            field=models.ManyToManyField(blank=True, null=True, to='consultas.datatreinamento'),
        ),
    ]
